export default function Head() {
	return (
		<>
			<title>VOICES</title>
			<meta content='width=device-width, initial-scale=1' name='viewport' />
			<meta name='description' content='Generated by create next app' />
			<meta name='theme-color' content='#0f0f11' />
			<link rel='icon' href='/favicon.ico' />
		</>
	);
}
